CXX = em++
PROJECT_NAME = flappy

#RAYLIB_PATH = /data/data/com.termux/files/home/github/raylib
RAYLIB_PATH = raylib

CXXFLAGS = -O2 -Wall -std=c++17 -DPLATFORM_WEB \
           -I$(RAYLIB_PATH)

LDFLAGS = -L$(RAYLIB_PATH)/web \
          -lraylib.web \
          -s USE_GLFW=3 \
          -s ALLOW_MEMORY_GROWTH=1 \
          --shell-file $(RAYLIB_PATH)/minshell.html \
          --preload-file assets

SRC = main.cpp
WEB_DIR = web

all: $(WEB_DIR)/$(PROJECT_NAME).html

$(WEB_DIR)/$(PROJECT_NAME).html: $(SRC)
	mkdir -p $(WEB_DIR)
	$(CXX) $(SRC) $(CXXFLAGS) $(LDFLAGS) -o $@

clean:
	rm -rf $(WEB_DIR)/*